spring:
  cloud:
    openfeign:
      client:
        config:
          clients:
            url: http://localhost:8765/clients
          catalog:
            url: http://localhost:8765/catalog
          storage:
            url: http://localhost:8765/storage
          documents:
            url: http://localhost:8765/documents
          nomenclature:
            url: http://localhost:8765/nomenclature
          transportation:
            url: http://localhost:8765/transportation
          processor:
            url: http://localhost:8765/processor
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-url: http://localhost:9090/realms/master
          # jwk-set-uri: http://localhost:9090/realms/master/protocol/openid-connect/certs

api:
  basic-uri:
    clients: http://localhost:8765/clients/
    catalog: http://localhost:8765/catalog/
    storage: http://localhost:8765/storage/
    documents: http://localhost:8765/documents/
    nomenclature: http://localhost:8765/nomenclature/
    transportation: http://localhost:8765/transportation/
    processor: http://localhost:8765/processor/

# tmpVar: configServer